mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

polls/urls.py
"""Defines URL pattern for application Polls"""
from django.urls import path
from . import views

#name space help distinguish this urls.py from files in other apps
app_name = 'polls'

urlpatterns=[
    # Home page
    path('', views.index, name='index'),
    # Page that shows all question
    path('questions/', views.questions, name='questions'),
    path('questions/<int:question_id>', views.question, name='question'),
    path('new_question/', views.new_question, name='new_question'),
    path('new_choice/<int:question_id>', views.new_choice, name='new_choice'),
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    #Add owner
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models

# Create your models here.

polls/forms.py
from django import forms
from .models import Question, Choice

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']
        labels = {'question_text': 'Your text'}

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']
        labels = {'choice_text': 'Your choice'}
        widgets = {'choice_text': forms.Textarea(attrs={'cols':80})}

polls/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice
from .forms import QuestionForm, ChoiceForm

from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    """The home page for Polls app."""
    return render(request, 'polls/index.html')
# Login required
@login_required
def questions(request):
    """Show all questions"""
    # Query the database for all questions
    # questions = Question.objects.all()
    # Retrieve the questions whose owner matches the current user
    questions = Question.objects.filter(owner=request.user)
    # Context that will send to the template
    context = {'questions': questions}
    return render(request, 'polls/questions.html', context)

@login_required
def question(request, question_id):
    """Show a single question and all its choices"""
    # Select the question which id is question_id
    question = Question.objects.get(id=question_id)

    # Ensure the questin belongs to the current user
    if question.owner != request.user:
        raise Http404


    # Query all choice related to this question
    choices = question.choice_set.all()
    # Context
    context = {'question': question, 'choices': choices}
    return render(request, 'polls/question.html', context)

@login_required
def new_question(request):
    """Add a new question"""
    # Initially request method is GET
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = QuestionForm()
    else:
        # POST data submitted; process data.
        form = QuestionForm(data=request.POST)
        if form.is_valid():
            # form.save()
            # Associtating new question with the current user
            new_question = form.save(commit=False)
            new_question.owner = request.user
            new_question.save()
            return redirect('polls:questions')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'polls/new_question.html', context)

@login_required
def new_choice(request, question_id):
    """Add a new choice for particular question"""
    # Select the specific question to add new choice
    question = Question.objects.get(id=question_id)

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = ChoiceForm()
    else:
        # POST data submitted; process data.
        form = ChoiceForm(data=request.POST)
        if form.is_valid():
            # Create new choice object without saving it to the database
            new_choice = form.save(commit=False)
            # Set the question attribute of new_choice
            new_choice.question = question
            new_choice.save()
            return redirect('polls:question', question_id=question_id)

    # Display a blank or invalid form
    context = {'question': question, 'form': form}
    return render(request, 'polls/new_choice.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('polls:index')

    # Display a blink or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

polls/templates/polls/base.html
<p>
  <a href="{% url 'polls:index' %}">Polls</a>
</p>
<p>
  <a href="{% url 'polls:questions' %}">Questions</a>
</p>

<p>
{% if user.is_authenticated %}
  Hello, {{user.username}}.
  <a href="{% url 'users:logout' %}">Logout</a>
{% else %}
  <a href="{% url 'users:register' %}">Register</a>
  <a href="{% url 'users:login' %}">Log in</a>
{% endif %}
</p>
  
{% block content %}
{% endblock content %}

polls/templates/polls/index.html
{% extends 'polls/base.html'%}
{% block content %}
  <p>
    Polls app helps you investigate everything about student's life.
  </p>
{% endblock content %}

polls/templates/polls/new_choice.html
{% extends "polls/base.html" %}
{% block content %}
  <p><a href="{% url 'polls:question' question.id %}">{{question}}</a></p>
  <p>Add a new choice</p>
  <form action="{% url 'polls:new_choice' question.id %}" method='post'>
    {% csrf_token%}
	{{form.as_p}}
    <button name="submit">Add choice</button>
  </form>
{% endblock content %}

polls/templates/polls/new_question.html
{% extends "polls/base.html" %}
{% block content %}
  <p> Add new topic</p>
  <form action="{% url 'polls:new_question' %}" method='post'>
    {% csrf_token%}
	{{form.as_p}}
    <button name="submit">Add question</button>
  </form>
{% endblock content %}

polls/templates/polls/question.html
{% extends 'polls/base.html' %}
{% block content %}
  <p>Question: {{question}}</p>
  <p>Choices</p>
  <p>
    <a href="{% url 'polls:new_choice' question.id %}">Add new choice</a>
  </p>
  <ul>
  {% for choice in choices %}
    <li>{{choice}}</li>
  {% empty%}
    <li>There are no choices for this question yet</li>
  {% endfor %}
  </ul>
{% endblock content%}

polls/templates/polls/questions.html
{% extends "polls/base.html" %}
{% block content%}
  <p>List of questions</p>
  <ul>
    {% for question in questions %}
	  <li>
	    <a href="{% url 'polls:question' question.id %}">{{question}}</a>
	  </li>
	{% empty %}
	  <li>No questions have been added yet</li>
	{% endfor %}
  </ul>
  <a href="{% url 'polls:new_question' %}">Add a new question</a>
{% endblock content%}